# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 28c9ea5b9050705d35bdf0dbc01642f76fc0addafd78d2d3392cec1e22a24dea4f21cc58b5ba85e717ef0f3f6e2918711c6fac4694904c7aeb8f947f59fa746f

test:
  secret_key_base: 405aa3722ca3ced2ef4d73619bb035bacc8848b4683850a73a7ed1ae63f9a8b6509fc4e99eb50d6216dda08eea67a2a7292dfbf66eecc93bf33f09c1144bcfc2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
